
export const CHECK_DUPLICATE_EMAIL_TO_SPRING = 'CHECK_DUPLICATE_EMAIL_TO_SPRING';
export const REQUEST_CURRENT_USER_NICKNAME_FROM_SPRING = 'REQUEST_CURRENT_USER_NICKNAME_FROM_SPRING';
export const CHECK_DUPLICATE_NICKNAME_TO_SPRING = 'CHECK_DUPLICATE_NICKNAME_TO_SPRING';

export const REQUEST_UPLOADER_NOVEL_INFO_LIST = 'REQUEST_UPLOADER_NOVEL_INFO_LIST';

export const REQUEST_BOARD_LIST_FROM_SPRING = 'REQUEST_BOARD_LIST_FROM_SPRING'
export const REQUEST_BOARD_FROM_SPRING = 'REQUEST_BOARD_FROM_SPRING'
export const REQUEST_NOVEL_EPISODE_LIST = 'REQUEST_NOVEL_EPISODE_LIST'


export const REQUEST_SIGN_IN_TOKEN_FROM_SPRING = 'REQUEST_SIGN_IN_TOKEN_FROM_SPRING'
export const SIGN_IN_VALUE = 'SING_IN_VALUE'
export const USER_TOKEN = 'USER_TOKEN'